nginx:
    image: nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    links:
    - tomcat

tomcat:
    image: tomcat:8
    volumes:
    - ./server.xml:/usr/local/tomcat/conf/server.xml:ro
    ports:
    - 8080:8080